### ISSUE TITLE
update readme 

### ISSUE THREAD

**Issue by hackertron** [hackertron/CryptSteg#11]

**Comment by rudr4x5h** [comment]
@hackertron do you just want the images to be described in the readme?
and can I help in this?

**Comment by hackertron** [comment]
yeah kind of . Just add screenshot of atleast 1 more challenge , that willl do for this issue .  

So setup the project on your system and just add screenshot of 1 more level .

**Comment by rudr4x5h** [comment]
Sure, thanks
